version: "3.8"
services:
  cassandra-0:
    image: cassandra:latest
    hostname: cassandra-0
    restart: always
    ports:
      - "7000:7000"
      - "9042:9042"
    volumes:
      - /opt/cassandra-node-0/commitlog:/var/lib/cassandra/commitlog
      - /opt/cassandra-node-0/hints:/var/lib/cassandra/hints
      - /opt/cassandra-node-0/data:/var/lib/cassandra/data
      - /opt/cassandra-node-0/saved_caches:/var/lib/cassandra/saved_caches
      - /opt/cassandra-node-0/logs:/var/log/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra-0,cassandra-1
      - CASSANDRA_CLUSTER_NAME=cluster
#      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M

  cassandra-1:
    image: cassandra:latest
    hostname: cassandra-1
    restart: always
    ports:
      - "7001:7000"
      - "9043:9042"
    volumes:
      - /opt/cassandra-node-1/data:/var/lib/cassandra/data
      - /opt/cassandra-node-1/commitlog:/var/lib/cassandra/commitlog
      - /opt/cassandra-node-1/hints:/var/lib/cassandra/hints
      - /opt/cassandra-node-1/saved_caches:/var/lib/cassandra/saved_caches
      - /opt/cassandra-node-1/logs:/var/log/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra-0,cassandra-1
      - CASSANDRA_CLUSTER_NAME=cluster
#      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M

  cassandra-2:
    image: cassandra:latest
    hostname: cassandra-2
    restart: always
    ports:
      - "7002:7000"
      - "9044:9042"
    volumes:
      - /opt/cassandra-node-2/data:/var/lib/cassandra/data
      - /opt/cassandra-node-2/commitlog:/var/lib/cassandra/commitlog
      - /opt/cassandra-node-2/hints:/var/lib/cassandra/hints
      - /opt/cassandra-node-2/saved_caches:/var/lib/cassandra/saved_caches
      - /opt/cassandra-node-2/logs:/var/log/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra-0,cassandra-1
      - CASSANDRA_CLUSTER_NAME=cluster
#      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M